export const AUTH_START_REQUEST = 'AUTH_START_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";

export const ISSUES_GET_REQUEST = "ISSUES_GET_REQUEST";
export const ISSUES_GET_SUCCESS = "ISSUES_GET_SUCCESS";
export const ISSUES_GET_FAIL = "ISSUES_GET_FAIL";

export const ORGS_GET_REQUEST = "ORGS_GET_REQUEST";
export const ORGS_GET_SUCCESS = "ORGS_GET_SUCCESS";
export const ORGS_GET_FAIL = "ORGS_GET_FAIL";

export const USERS_GET_REQUEST = "USERS_GET_REQUEST";
export const USERS_GET_SUCCESS = "USERS_GET_SUCCESS";
export const USERS_GET_FAIL = "USERS_GET_FAIL";

export const ORG_USERS_GET_REQUEST = "ORG_USERS_GET_REQUEST";
export const ORG_USERS_GET_SUCCESS = "ORG_USERS_GET_SUCCESS";
export const ORG_USERS_GET_FAIL = "ORG_USERS_GET_FAIL";

export const ORG_CREATE_REQUEST = "ORG_CREATE_REQUEST";
export const ORG_CREATE_SUCCESS = "ORG_CREATE_SUCCESS";
export const ORG_CREATE_FAIL = "ORG_CREATE_FAIL";

export const PROFILE_GET_REQUEST = "PROFILE_GET_REQUEST";
export const PROFILE_GET_SUCCESS = "PROFILE_GET_SUCCESS";
export const PROFILE_GET_FAIL = "PROFILE_GET_FAIL";

export const ADMINS_GET_REQUEST = 'ADMINS_GET_REQUEST';
export const ADMINS_GET_SUCCESS = 'ADMINS_GET_SUCCESS';
export const ADMINS_GET_FAIL = 'ADMINS_GET_FAIL';

export const ORG_STATUS_REQUEST = 'ORG_STATUS_REQUEST';
export const ORG_STATUS_SUCCESS = 'ORG_STATUS_SUCCESS';
export const ORG_STATUS_FAIL = 'ORG_STATUS_FAIL';

export const AVATAR_ULPOAD_REQUEST = 'AVATAR_ULPOAD_REQUEST';
export const AVATAR_ULPOAD_SUCCESS = 'AVATAR_ULPOAD_SUCCESS';
export const AVATAR_ULPOAD_FAIL = 'AVATAR_ULPOAD_FAIL';

export const RESOLVE_ISSUE_REQUEST = 'RESOLVE_ISSUE_REQUEST';
export const RESOLVE_ISSUE_SUCCESS = 'RESOLVE_ISSUE_SUCCESS';
export const RESOLVE_ISSUE_FAIL = 'RESOLVE_ISSUE_FAIL';

export const ORG_PROFILE_REQUEST = 'ORG_PROFILE_REQUEST';
export const ORG_PROFILE_SUCCESS = 'ORG_PROFILE_SUCCESS';
export const ORG_PROFILE_FAIL = 'ORG_PROFILE_FAIL';

export const ORGADMIN_PROFILE_REQUEST = "ORGADMIN_PROFILE_REQUEST";
export const ORGADMIN_PROFILE_SUCCESS = "ORGADMIN_PROFILE_SUCCESS";
export const ORGADMIN_PROFILE_FAIL = "ORGADMIN_PROFILE_FAIL";

export const ORG_ISSUES_REQUEST = "ORG_ISSUES_REQUEST";
export const ORG_ISSUES_SUCCESS = "ORG_ISSUES_SUCCESS";
export const ORG_ISSUES_FAIL = "ORG_ISSUES_FAIL";

export const ADMININFO_UPD_REQUEST = "ADMININFO_UPD_REQUEST";
export const ADMININFO_UPD_SUCCESS = "ADMININFO_UPD_SUCCESS";
export const ADMININFO_UPD_FAIL = "ADMININFO_UPD_FAIL";

export const UPDATE_ORG_REQUEST = "UPDATE_ORG_REQUEST";
export const UPDATE_ORG_SUCCESS = "UPDATE_ORG_SUCCESS";
export const UPDATE_ORG_FAIL = "UPDATE_ORG_FAIL";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";

export const UPDATE_AVATAR_REQUEST = "UPDATE_AVATAR_REQUEST";
export const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS";
export const UPDATE_AVATAR_FAIL = "UPDATE_AVATAR_FAIL";

export const ORGRESOLVE_ISSUE_REQUEST = "ORGRESOLVE_ISSUE_REQUEST";
export const ORGRESOLVE_ISSUE_SUCCESS = "ORGRESOLVE_ISSUE_SUCCESS";
export const ORGRESOLVE_ISSUE_FAIL = "ORGRESOLVE_ISSUE_FAIL";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

export const USER_ORGINFO_REQUEST = "USER_ORGINFO_REQUEST";
export const USER_ORGINFO_SUCCESS = "USER_ORGINFO_SUCCESS";
export const USER_ORGINFO_FAIL = "USER_ORGINFO_FAIL";

export const USER_AVATAR_REQUEST = "USER_AVATAR_REQUEST";
export const USER_AVATAR_SUCCESS = "USER_AVATAR_SUCCESS";
export const USER_AVATAR_FAIL = "USER_AVATAR_FAIL";

export const USERINFO_UPD_REQUEST = "USERINFO_UPD_REQUEST";
export const USERINFO_UPD_SUCCESS = "USERINFO_UPD_SUCCESS";
export const USERINFO_UPD_FAIL = "USERINFO_UPD_FAIL";

export const USER_ISSUES_REQUEST = "USER_ISSUES_REQUEST";
export const USER_ISSUES_SUCCESS = "USER_ISSUES_SUCCESS";
export const USER_ISSUES_FAIL = "USER_ISSUES_FAIL";

export const RAISED_ISSUES_REQUEST = "RAISED_ISSUES_REQUEST";
export const RAISED_ISSUES_SUCCESS = "RAISED_ISSUES_SUCCESS";
export const RAISED_ISSUES_FAIL = "RAISED_ISSUES_FAIL";

export const RESOLVE_ISSUES_REQUEST = "RESOLVE_ISSUES_REQUEST";
export const RESOLVE_ISSUES_SUCCESS = "RESOLVE_ISSUES_SUCCESS";
export const RESOLVE_ISSUES_FAIL = "RESOLVE_ISSUES_FAIL";

export const CREATE_ISSUE_REQUEST = "CREATE_ISSUE_REQUEST";
export const CREATE_ISSUE_SUCCESS = "CREATE_ISSUE_SUCCESS";
export const CREATE_ISSUE_FAIL = "CREATE_ISSUE_FAIL";